testando2: 
	gcc -g -ansi -std=c99 -o exe testando2.c leitor.c -lSDL -lSDL_ttf -I. -lncurses

install:
	sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libncurses-dev 

run:
	./exe

clean:
	rm exe